[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 1000
via_ir = true
ffi = true

[profile.lite]
optimizer = false

# Multiple Solidity version support
solc = "0.8.20" # Specify multiple compiler versions
allow_paths = [
    "./src",
    "./lib",
] # Allow compiler to access all source directories
auto_detect_solc = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[rpc_endpoints]
base = "${BASE_RPC_URL}"

# forge script script/Deploy.s.sol:EndpointDeploymentScript --rpc-url $BASE_RPC_URL --broadcast  --via-ir
# forge script script/Deploy.s.sol:EndpointDeploymentScript --fork-url $BASE_RPC_URL --broadcast --via-ir
