// SPDX-License-Identifier: GPL-2.0-or-later
pragma solidity ^0.8.20;

string constant ERR_TRANSFER_FAILED = "ERR_TRANSFER_FAILED";

string constant ERR_INVALID_AMOUNT_IN = "ERR_INVALID_AMOUNT_IN";
string constant ERR_INVALID_AMOUNT_IN_MAX = "ERR_INVALID_AMOUNT_IN_MAX";

string constant ERR_INVALID_SEND_AMOUNT = "ERR_INVALID_SEND_AMOUNT";

string constant ERR_INVALID_AMOUNT_OUT = "ERR_INVALID_AMOUNT_OUT";

string constant ERR_INVLIAD_BALANCE_IN = "ERR_INVLIAD_BALANCE_IN";

string constant ERR_LOW_AMOUNT_IN = "ERR_LOW_AMOUNT_IN";
string constant ERR_INVALID_ALLOWANCE = "ERR_INVALID_ALLOWANCE";
// string constant ERR_OVERFLOW_TARGET_BASE = "ERR_OVERFLOW_TARGET_BASE";

string constant ERR_INSUFFICIENT_RESERVE = "ERR_INSUFFICIENT_RESERVE";

string constant ERR_INSUFFICIENT_INPUT_AMOUNT = "ERR_INSUFFICIENT_INPUT_AMOUNT";

string constant INSUFFICIENT_INPUT_AMOUNT = "INSUFFICIENT_INPUT_AMOUNT";
string constant ERR_INVALID_TO = "ERR_INVALID_TO";

string constant ERR_HIGH_SLIPPAGE = "ERR_HIGH_SLIPPAGE";

string constant ERR_INVALID_SLIPPAGE = "ERR_INVALID_SLIPPAGE";

string constant ERR_ONLY_FACTORY = "ERR_ONLY_FACTORY";

string constant ERR_LOCK = "ERR_LOCK";

string constant ERR_INVALID_K = "ERR_INVALID_K";

string constant ERR_ONLY_OWNER = "ERR_ONLY_OWNER";

string constant ERR_ONLY_ONCE_MINT = "ERR_ONLY_ONCE_MINT";

string constant ERR_INVALID_FEE = "ERR_INVALID_FEE";

string constant ERR_INVALID_SIGNATURE = "ERR_INVALID_SIGNATURE";

string constant ERR_EXPIRED = "ERR_EXPIRED";

string constant ERR_OVERFLOW_TARGET = "ERR_OVERFLOW_TARGET";

string constant ERR_INSUFFICIENT_FEE = "ERR_INSUFFICIENT_FEE";

string constant ERR_INVALID_PATH = "ERR_INVALID_PATH";

string constant EXCESSIVE_INPUT_AMOUNT = "EXCESSIVE_INPUT_AMOUNT";

string constant ERR_INVALID_SEND_NAD = "ERR_INVALID_SEND_NAD";

string constant ERR_ONLY_ENDPOINT = "ERR_ONLY_ENDPOINT";
